[package]
name = "groffol"
version = "0.1.0"
authors = ["Erarnitox <erarnitox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
