.R1
accumulate
database bib.ref
move-punctuation
.R2

.TL
A test Document

.AU
Erarnitox - David Partsch
.AI
DropSoft
.DA

.AB
.PP
This Document is an example Document on how to use drop-markdown.Which is a wrapper around groff for easy writing for papers to be publishedon dropsoft.org
.AE

.bp

.NH 1
Heading
.XS
Heading
.XE
.PP
This was and example heading.  

a new line.The same line
.NH 2
A sub heading
.XS
A sub heading
.XE
.NH 3
And so on
.XS
And so on
.XE
.PP
You get the point.
.NH 4
down deeep
.XS
down deeep
.XE
.PP
Goes down to 6 sub levels
.QP
This is a small quoted paragraph. I really hope this will work!